version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - run:
          name: run tests
          command: pipenv run pytest

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  integrate:
    docker:
      - image: docker:stable

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "batect.yml" }}
            - cache-
      - run:
          name: run tests
          command: ./batect integration-test

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.batect
workflows:
  version: 2
  build_and_integrate:
    jobs:
      - build
      - integrate